import { Toaster } from "@/components/ui/sonner";
import { getLocaleMessages } from "@/i18n/server";
import '@/lib/fontawesome';
import { Providers } from "@/store/providers";
import InitAuth from "@/utils/init-auth";
import type { Metadata } from "next";
import { NextIntlClientProvider } from 'next-intl';
// import { Barlow } from "next/font/google";
import { Suspense } from "react";
import "./globals.css";

// const barlow = Barlow({
//   subsets: ["latin"],
//   variable: "--font-barlow",
//   weight: ["400", "500", "600", "700", "800"],
// });

export const metadata: Metadata = {
  title: "Nguyen Anh Group",
  description: "Generated by Nguyen Anh Group Development Team",
};

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  const { locale, messages } = await getLocaleMessages();

  return (
    <html lang={locale}>
      <head>
        {process.env.NEXT_PUBLIC_API_URL && (
          <link rel="preconnect" href={new URL(process.env.NEXT_PUBLIC_API_URL).origin} />
        )}
      </head>
      {/* <body className={`${barlow.variable} font-sans`}> */}
      <body>
        <Providers>
          <Suspense fallback={null}>
            <InitAuth />
          </Suspense>

          <NextIntlClientProvider locale={locale} messages={messages}>
            {children}
          </NextIntlClientProvider>

          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
