import { Toaster } from "@/components/ui/sonner";
import { getLocaleMessages } from "@/i18n/server";
import '@/lib/fontawesome';
import { Providers } from "@/store/providers";
import InitAuth from "@/utils/init-auth";
import type { Metadata } from "next";
import { NextIntlClientProvider } from 'next-intl';
import { Instrument_Sans } from "next/font/google";
import { Suspense } from "react";
import "./globals.css";

const instrumentSans = Instrument_Sans({
  subsets: ["latin"],
  variable: "--font-instrument-sans",
});

export const metadata: Metadata = {
  title: "Nguyen Anh Group",
  description: "Generated by Nguyen Anh Group Development Team",
};

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  const { locale, messages } = await getLocaleMessages();

  return (
    <html lang={locale}>
      <head>
        {process.env.NEXT_PUBLIC_API_URL && (
          <link rel="preconnect" href={new URL(process.env.NEXT_PUBLIC_API_URL).origin} />
        )}
      </head>
      <body className={`${instrumentSans.variable} font-sans`}>
        <Providers>
          <Suspense fallback={null}>
            <InitAuth />
          </Suspense>

          <NextIntlClientProvider locale={locale} messages={messages}>
            {children}
          </NextIntlClientProvider>

          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
